# Generated by Django 4.1.7 on 2023-05-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacciones',
            new_name='Transaccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Transacciones_id_transacciones',
            new_name='Transaccion_id_transaccion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='id_transacciones',
            new_name='id_transaccion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='monto_transacciones',
            new_name='monto_transaccion',
        ),
    ]
